- build.gradle.kts
- nais/nais.yml
- src/main/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieController.kt
- src/main/kotlin/no/nav/faktureringskomponenten/metrics/MetricsConfig.kt
- src/main/kotlin/no/nav/faktureringskomponenten/metrics/MetrikkNavn.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
- src/main/resources/application.yml
Metrikkene postes iallefall på siden så tror det funker 🤷‍♀️ 
https://jira.adeo.no/browse/MELOSYS-5503
> 5503 Prøver meg på å legge til metrikker i prosjektet

- nais/vars-q1.json
- nais/vars-q2.json
[MELOSYS-5874](https://jira.adeo.no/browse/MELOSYS-5874)
Vi har noen applikasjoner i dev-gcp med ingresser som skal slås av 2. mai. 
https://nav-it.slack.com/archives/C01DE3M9YBV/p1677747333208699
> 5874: Bytt ingress for dev-miljø

- src/main/kotlin/no/nav/faktureringskomponenten/service/cronjob/FakturaBestillCronjob.kt
Justerer for å la OEBS slippe å vente i en hel dag for hver gang de tester.
> NOJIRA: Juster cron jobben  til hver 5 minutt i testfase

- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Faktura.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/FakturaMottatt.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/FakturaMottattStatus.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/FakturaStatus.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/repositories/FakturaMottattRepository.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/repositories/FakturaRepository.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaMottattService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/FakturaMottattConsumer.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/dto/FakturaMottattDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaMottattMapper.kt
- src/main/resources/db/migration/V9__ny_tabell_melding_OEBS.sql
- src/test/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/FakturaMottattConsumeStopperVedFeilIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/FakturaMottattConsumerIT.kt
- src/test/resources/logback-test.xml
Konsumerer fra kafka kø oebs legger melding på, lagrer det så i en egen
tabell i databasen
https://jira.adeo.no/browse/MELOSYS-5988
https://jira.adeo.no/browse/MELOSYS-5989
> 5988|5989: Konsumerer og lagerer melding fra OEBS

- nais/nais.yml
- nais/vars-prod.json
- nais/vars-q1.json
- nais/vars-q2.json
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/FakturaMottatt.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaMottattService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/KafkaManglendeFakturabetalingProducer.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/ManglendeFakturabetalingProducer.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/config/KafkaConfig.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/config/ManglendeFakturabetalingSerializer.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/dto/ManglendeFakturabetalingDto.kt
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaMottattServiceIT.kt
- src/test/resources/application-itest.yml
Melosys API kan lese fra kafka kø som opprettes her.
https://jira.adeo.no/browse/MELOSYS-6046
> 6046: Lager kafka kø

- src/main/kotlin/no/nav/faktureringskomponenten/controller/FakturaController.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieController.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/dto/FakturaTilbakemeldingResponseDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/mapper/ModelDtoMapperExtensions.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/repositories/FakturaMottattRepository.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaMottattService.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/FakturaMottattConsumerIT.kt
Ta den andre pr først som handler om opprette kafka kø
https://jira.adeo.no/browse/MELOSYS-6047
> 6047: Lager endepunkt for å hente faktura info

- src/main/kotlin/no/nav/faktureringskomponenten/controller/AdminController.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/FakturaMottattConsumer.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/FakturaMottattConsumeStopperVedFeilIT.kt
stop start og resett offset fungerer ikke for Aiven. Vi bruker dql istedenfor resett av offfset
> 5990 fjerner admin kode som ikke fungerer

- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGeneratorTest.kt
https://jira.adeo.no/browse/MELOSYS-6063
Fakturalinjer for hvert kalenderår i egen faktura
> 6063 egen faktura per kalenderår

- .github/workflows/deploy-manuelt.yml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-q2.yaml
- build.gradle.kts
- nais/nais.yml
- nais/unleash-apitoken.yml
- nais/vars-prod.json
- nais/vars-q1.json
- nais/vars-q2.json
- src/main/kotlin/no/nav/faktureringskomponenten/featuretoggle/FeatureToggleConfig.kt
- src/main/kotlin/no/nav/faktureringskomponenten/featuretoggle/LocalUnleash.kt
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/resources/application-itest.yml
Legger inn mulighet til å bruke toggle
> NO JIRA unleash implement

- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGeneratorTest.kt
https://jira.adeo.no/browse/MELOSYS-6138
> MELOSYS 6138

- src/main/kotlin/no/nav/faktureringskomponenten/controller/dto/FakturaTilbakemeldingResponseDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/mapper/ModelDtoMapperExtensions.kt
Må vise fakturanummer i frontend, må ha det i respons.
https://jira.adeo.no/browse/MELOSYS-5957
> MELOSYS 5957  fakturanummer

- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Faktura.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaLinjeGenerator.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGeneratorTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieServiceTest.kt
Bare litt opprydding og forenkling før jeg endrer koden mer for https://jira.adeo.no/browse/MELOSYS-6060
> 6060 løpende avregning - opprydding

- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/FakturaLinje.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Fakturaserie.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
- src/main/resources/db/migration/V14__avregning_faktura_id.sql
- src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaMottattServiceIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieServiceTest.kt
- Felt for å lagre faktura som brukes ved avregning
- Nødvendig refaktorering for https://jira.adeo.no/browse/MELOSYS-6060
- Fikser feil ved erstatning av faktura
> 6060 felt for å lagre faktura som brukes ved avregning

- src/main/kotlin/no/nav/faktureringskomponenten/controller/dto/FakturaLinjeResponseDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/mapper/ModelDtoMapperExtensions.kt
En del av
https://jira.adeo.no/browse/MELOSYS-6172
> 6172: TOGGLE Antall linjer i respons

- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Faktura.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandler.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningsfakturaGenerator.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/Avregningsperiode.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapper.kt
- src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandlerTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningsfakturaGeneratorTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapperTest.kt
https://jira.adeo.no/browse/MELOSYS-6060
- Tittel for avregningsfaktura og test av linjebeskrivelse for OEBS fakturaer
- Egen pakke for avregning
> 6060 loepende avregning beskrivelse

- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/FakturaLinje.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandler.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningsfakturaGenerator.kt
- src/main/resources/db/migration/V17__avregningsbeloep.sql
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandlerTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningsfakturaGeneratorTest.kt
https://jira.adeo.no/browse/MELOSYS-6060
- Lagring av avregningsbeløp i fakturalinjer
- Bruk av lagret avregningsbeløp ved flere avregninger på rad
> MELOSYS 6060 avregningsbeloep lagring

- src/main/kotlin/no/nav/faktureringskomponenten/controller/dto/FakturaResponseDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/dto/FakturaTilbakemeldingResponseDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/mapper/ModelDtoMapperExtensions.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/EksternFakturaStatus.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Faktura.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/EksternFakturaStatusMapper.kt
- src/main/resources/db/migration/V20__legg_til_faktura_nummer.sql
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningIT.kt
Når det ikke er fakturanummer på alle fakturaer som skal avregnes, skal
vi feile det og gi feilmelding.
https://jira.adeo.no/browse/MELOSYS-6190
> 6190: TOGGLE Avregning skal feile når det ikke er fakturanummer 

- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningsfakturaGenerator.kt
https://jira.adeo.no/browse/MELOSYS-6060
> 6060: Mangler referanse til faktura. Uten denne fungerer ikke findByReferanseNr

- src/main/kotlin/no/nav/faktureringskomponenten/controller/dto/FullmektigDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/mapper/ModelDtoMapperExtensions.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Fullmektig.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGenerator.kt
- src/main/resources/db/migration/V21__fjerner_fullmektig_kontaktperson.sql
- src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGeneratorTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieServiceTest.kt
Fjerner kontaktperson fra både dto og database-objektet. Det ble ikke brukt så det var ikke mye annet å fjerne
[MELOSYS-5905](https://jira.adeo.no/browse/MELOSYS-5905)
https://nav-it.slack.com/archives/C01CFP7SL4Q/p1698132992027959?thread_ts=1698070289.640419&cid=C01CFP7SL4Q
> 5905 DB TOGGLE Fjernet kontaktperson fra fullmektig

- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaLinjeGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaLinjeGeneratorTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGeneratorTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapperTest.kt
> 6205: TOGGLE Revert periode endringen

- src/main/kotlin/no/nav/faktureringskomponenten/controller/AdminController.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/EksternFakturaStatusConsumer.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/EksternFakturaStatusConsumeStopperVedFeilIT.kt
Vi må ha tilgang til å styre consumeren vår, sette/hoppeover offset osv. Gammel kode Rune har skrevet, jeg tar den inn igjen
> NO_JIRA: Tar inn endepunkter for kafka start,stop, endre offset

- src/main/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieController.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/dto/FakturamottakerRequestDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/mapper/ModelDtoMapperExtensions.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Fakturaserie.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturamottakerDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
- src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieServiceTest.kt
Nytt endepunkt for endring av fakturamottaker. Tenker det kun skal endre dersom det er gjenstående fakturaer som skal gå ut og det faktisk er endring i mottakeren (fullmektig eller bruker).
https://jira.adeo.no/browse/MELOSYS-6074
> 6074 TOGGLE Endepunkt for endring av fakturamottaker

- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGeneratorTest.kt
https://jira.adeo.no/browse/MELOSYS-6224
> 6229 TOGGLE Sortering fakturalinjer

- src/main/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusService.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/EksternFakturaStatusConsumerIT.kt
https://jira.adeo.no/browse/MELOSYS-6224
> 6224 TOGGLE Filtrere bort duplikater

- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningsfakturaGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandlerTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningIT.kt
https://jira.adeo.no/browse/MELOSYS-6229
> 6229 TOGGLE  avregning fakturalinje sortering

- src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapper.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapperTest.kt
https://jira.adeo.no/browse/MELOSYS-6223
> 6223: TOGGLE Ikke sende fakturanummer i faktura

- .idea/inspectionProfiles/Project_Default.xml
- src/main/kotlin/no/nav/faktureringskomponenten/config/PersistenceConfig.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/mapper/ModelDtoMapperExtensions.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/BaseEntity.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/EksternFakturaStatus.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Faktura.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/FakturaLinje.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/FakturaMottakFeil.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Fakturaserie.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandler.kt
- src/main/resources/db/migration/V22__opprettet_tidspunkt.sql
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningIT.kt
- src/test/resources/logback-test.xml
Poenget er å lagre opprettet tidspunkt for data pga. etterlevelse og feilsøking.
BaseEntity gjør det lettere å legge til noe i fremtiden, f.eks. opprettetAv.
> MELOSYS 6238  auditing

- nais/nais.yml
- src/test/kotlin/no/nav/faktureringskomponenten/testutils/PostgresTestContainerBase.kt
- Bump postgres + sett timezone
> MELOSYS 6108 bump postgres

- .github/workflows/codeql.yml
- build.gradle.kts
https://jira.adeo.no/browse/MELOSYS-5809
> 5809 Lag codeql.yml

- src/main/kotlin/no/nav/faktureringskomponenten/domain/repositories/FakturaRepository.kt
- src/main/kotlin/no/nav/faktureringskomponenten/featuretoggle/FeatureToggleConfig.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/EksternFakturaStatusConsumer.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/EksternFakturaStatusConsumerIT.kt
https://jira.adeo.no/browse/MELOSYS-6284
> 6284 TOGGLE Feilhåndtering og rekjøring av feilede fakturaer

- src/main/kotlin/no/nav/faktureringskomponenten/controller/AuditorAwareFilter.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/BaseEntity.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Fakturaserie.kt
- src/main/resources/db/migration/V24__fakturaserie_endret.sql
- src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt
Auditing for endringer i Fakturaserie https://jira.adeo.no/browse/MELOSYS-6238
> 6238 Endret av og tidspunkt i Fakturaserie

- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaGeneratorTest.kt
https://jira.adeo.no/browse/MELOSYS-6297
> 6297 datoBestilt settes korrekt

- src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapper.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapperTest.kt
https://jira.adeo.no/browse/MELOSYS-6294
> 6294 Beskrivelse på faktura dto skal ikke bruke dagens dato men perioden

- src/main/kotlin/no/nav/faktureringskomponenten/domain/repositories/FakturaRepository.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingService.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceIT.kt
https://nav-it.slack.com/archives/C03UZCM7RS5/p1701679425408699?thread_ts=1701678569.866429&cid=C03UZCM7RS5
> NOJIRA: Ikke bestill feilede fakturaer i cron job

- build.gradle.kts
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaGeneratorTest.kt
https://jira.adeo.no/browse/MELOSYS-6315
fakturaDato er før dagens
fakturaDato er i samme kvartal som dagens
fakturaDato er i neste kvartal, men kjøring den 19 i siste måned i kvartal er forbi
> 6315 DatoBestilt skal settes til dagens

- .github/workflows/codeql.yml
- .github/workflows/deploy-q2.yaml
https://jira.adeo.no/browse/MELOSYS-5809
> 5809 Legge inn codeql, kjører 1:41 AM every Friday. som MELOSYS-API

- src/main/kotlin/no/nav/faktureringskomponenten/domain/repositories/FakturaRepository.kt
- src/main/kotlin/no/nav/faktureringskomponenten/metrics/FakturaFeiletMetrikkerBinder.kt
- src/main/kotlin/no/nav/faktureringskomponenten/metrics/MetrikkNavn.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaService.kt
- src/test/kotlin/no/nav/faktureringskomponenten/architecture/ArkitekturTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaGeneratorTest.kt
Lager både gauge og counter for å samle på antalle feilede faktura og kunne lage alarmer i Grafana.
> 6362: Faktura med status Feil i metrikker

- src/main/kotlin/no/nav/faktureringskomponenten/controller/AdminController.kt
Den logikken skulle vært omvendt.
> NOJIRA: Fiks logisk feil i if-setting på simulert manglende betaling

- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Faktura.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandler.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningsfakturaGenerator.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/Avregningsperiode.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandlerTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningsfakturaGeneratorTest.kt
https://jira.adeo.no/browse/MELOSYS-6388
> 6388 avregning refererer nå til første positive faktura

- .github/workflows/deploy-dev.yaml
Det skal testes en del i Q1 den neste perioden. Derfor ønsker vi også å deploye til q1 ved merge.
> NOJIRA: Deploy til både Q1 og Q2 ved merge

- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/dto/FakturaBestiltDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapper.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapperTest.kt
…i integrasjon mot OEBS
https://nav-it.slack.com/archives/C05AYQKUC0K/p1706182820838159
> NOJIRA: Rename kreditReferanseNr -> kredriteringFakturaRef

- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/dto/FakturaBestiltDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapper.kt
- src/test/kotlin/no/nav/faktureringskomponenten/TestFacktoryDsl.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapperTest.kt
:hankey: -> krediteringFakturaRef
> NOJIRA DOEBS: Fiks typo kredriteringFakturaRef -> krediteringFakturaRef

- nais/nais.yml
- nais/vars-prod.json
- nais/vars-q1.json
- nais/vars-q2.json
Vi har alerede noe tilgangsstyring under accessPolicy hvor melosys-web og api har les og skriv.
Legger inn melosys innlogging tilgang på claims og allowAllUsers til false
https://jira.adeo.no/browse/MELOSYS-6348
> 6348 Tilgangsstyring

- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandler.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandlerTest.kt
Dersom melosys-api sender nye perioder og der man i tillegg har en eller flere fakturaer som ikke overlapper med nye periodene, må disse fakturaene krediteres, ettersom det vil tolkes som at beløp for disse periodene nå er 0.
Eksempel:
Førstegangsvedtak med periode fra 01.01.2020 - 31.12.2022, der det er plussbeløp for alle tre årene. Resulterer i 3 faktura sendt til bruker.
Andregangsvedtak: Kun to perioder sendes over fra Melosys, 01.01.2020-31.12.2020 og 01.01.2022-31.12.2022. Vil resultere i 3 avregningsfakturaer. Uten denne PR'en vil ikke 2021 tas med.
> 6270: Avregne ikke-overlappende fakturaer

- src/main/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieController.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/FakturaStatus.kt
- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Fakturaserie.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaLinjeGenerator.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGenerator.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
- src/main/resources/application-local.yml
- src/main/resources/db/migration/V28__faktura_status_avbrutt.sql
- src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/itests/FakturaKanselleringIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaLinjeGeneratorTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/EksternFakturaStatusConsumerIT.kt
https://jira.adeo.no/browse/MELOSYS-6167
> 6167 DB Fakturaserie kansellerer alle tidligere serier

- src/main/kotlin/no/nav/faktureringskomponenten/domain/repositories/FakturaserieRepository.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
https://github.com/navikt/melosys-api/pull/2276
https://jira.adeo.no/browse/MELOSYS-6479
> 6479: Logg en error dersom samme person har flere aktive fakturaserier

- .github/workflows/codeql.yml
https://jira.adeo.no/browse/MELOSYS-6412
> 6412 fjern codeql on pull

- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaGeneratorTest.kt
… gjelder året etterpå
https://nav-it.slack.com/archives/CPSMP2GKT/p1712060629709149
> PRODFIX: Sjekk på kvartal dersom bestillingsdato er i år

- src/main/kotlin/no/nav/faktureringskomponenten/controller/AdminController.kt
https://jira.adeo.no/browse/MELOSYS-6539
> 6539: Nytt endepunkt for å endre fakturastatus

- src/main/kotlin/no/nav/faktureringskomponenten/controller/AdminController.kt
Logikken er feil på admin-endepunktet som gjør at statusendringer ikke er mulig
> 6539 / NOJIRA: Fiks feil logikk på statusendringer i admin-endepunkt

- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaGeneratorTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGeneratorTest.kt
https://jira.adeo.no/browse/MELOSYS-6569
> 6569 Ikke lag faktura dersom det ikke finner noen fakturalinjer

- src/main/kotlin/no/nav/faktureringskomponenten/controller/AdminController.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/AdminService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaService.kt
https://jira.adeo.no/browse/MELOSYS-6801
> 6801: Legg til endepunkt for kreditering av enkelfaktura

- src/main/kotlin/no/nav/faktureringskomponenten/service/AdminService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningsfakturaGenerator.kt
- src/test/kotlin/no/nav/faktureringskomponenten/PostgresTestContainerBase.kt
Klarte ikke lagre faktura, i tillegg var beskrivelse feil
https://jira.adeo.no/browse/MELOSYS-6801
tidligere PR: https://github.com/navikt/faktureringskomponenten/pull/189
> MELOSYS-6801: Fiks feil med lagring av faktura, fiks beskrivelse

- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/PeriodiseringUtil.kt
- src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieServiceTest.kt
https://jira.adeo.no/browse/MELOSYS-6957
2 tester som nå feiler etter fiks av 6957.
> 6957 fiks feil med manglende faktura

- .editorconfig
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/PeriodiseringUtil.kt
- src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/PeriodiseringUtilTest.kt
https://jira.adeo.no/browse/MELOSYS-6957
Fakturerbare perioder som overlapper med avregning kan være relevante
Hvis perioden ikke overlapper helt må vi bruker differansen.
> 6957 manglende fakturaer ved endring startperiode (2)

- src/main/kotlin/no/nav/faktureringskomponenten/controller/AdminController.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
Dermed vil alle kall til tilFaktura bruke toggle
https://jira.adeo.no/browse/MELOSYS-6993
> 6993 Ummiddelbar fakturering i testmiljø for alle fakturaer

- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/dto/FakturaBestiltDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapper.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceTest.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapperTest.kt
https://jira.adeo.no/browse/MELOSYS-7022
> 7022: Alltid sett dagens dato for faktureringsdato

- src/main/kotlin/no/nav/faktureringskomponenten/controller/dto/FakturaRequestDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaDto.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaserieServiceTest.kt
Fakturering for årsavregning skal kun referere til evt tidligere årsavrenging for samme år. Api sitt ansvar å sende riktig tidligereFakturaRef
https://jira.adeo.no/browse/MELOSYS-6552
> 6552 TOGGLE Årsavregning fakturering tidligere faktura er optional

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
Fjerne også tagging ved deploy til prod siden dette ikke er nødvendig lengre
https://jira.adeo.no/browse/MELOSYS-6983
> 6983 tag image med latest ved merge til master

- src/main/kotlin/no/nav/faktureringskomponenten/controller/AdminController.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusService.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/EksternFakturaStatusConsumer.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusServiceTest.kt
https://jira.adeo.no/browse/MELOSYS-7008
> 7008 Mulighet for å simulere manglende innbetaling i prod miljøer

- .github/workflows/deploy-dev.yaml
https://jira.adeo.no/browse/MELOSYS-7054
> 7054 Støtte for docker images med arm64 arkitektur

- src/main/kotlin/no/nav/faktureringskomponenten/config/SubjectHandler.kt
- src/main/kotlin/no/nav/faktureringskomponenten/controller/AuditorAwareFilter.kt
https://jira.adeo.no/browse/MELOSYS-6947
Satsendringsbehandlinger er automatiske og må kunne fakturere endringen automatisk.
Hent auditor fra token hvis den ikke finnes som header.
> 6947 Hent auditor fra token hvis den ikke finnes som header.

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-manuelt.yml
- .github/workflows/deploy-prod.yaml
https://jira.adeo.no/browse/MELOSYS-7153
> 7153: Publiser images til Google Artifact Registry

- src/main/kotlin/no/nav/faktureringskomponenten/domain/models/Innbetalingstype.kt
- src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapper.kt
- src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapperTest.kt
https://jira.adeo.no/browse/MELOSYS-7331
> 7331 DAPI årsavregning faktura beskrivelse

- src/main/resources/db/migration/V32__aarsavregning.sql
Glemte å legge på enum i db så validation feiler når man prøver å opprette faktura for årsavregning
> 7331 DB Legger på innbetaling type enum AARSAVREGNING

- nais/nais.yml
https://doc.nais.io/persistence/cloudsql/how-to/enable-auditing/
> NOJIRA G4P: Slå på auditlogging
