src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaMapper.kt

Setter derfor plusDays til 0L - antar det betyr at de sendes med en gang, istedenfor å vente til neste dag/natt.

NOJIRA Vi ønsker ikke å forsinke sending av faktura mens vi tester

---

src/main/kotlin/no/nav/faktureringskomponenten/controller/dto/FakturaserieRequestDto.kt
src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerTest.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturalinjeMapperTest.kt

Ref: https://nav-it.slack.com/archives/C01CFP7SL4Q/p1683879427862769?thread_ts=1683878879.815269&cid=C01CFP7SL4Q
Endret samtidig kjapt default betalingsintervall til KVARTAL: Muntlig diskusjon. Det er kvartalsmessig som brukes i avgiftssystemet idag, så det gir mer mening å ha dette som default istedenfor månedlig. Bruker kan heller ikke velge dette i søknaden så muligheten for å velge dette skal fjernes fra vedtak-steget. Det vil i den oppgaven bli viktig at vi har rett default.
https://jira.adeo.no/browse/MELOSYS-5906

5906 Overlappende perioder havner i samme faktura

---

src/main/kotlin/no/nav/faktureringskomponenten/service/beregning/BeløpBeregner.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/beregning/BeløpBeregnerTest.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaserieMapperTest.kt

https://jira.adeo.no/browse/MELOSYS-5900
skal støttes når man ganger antall med enhetspris

5900 Fakturalinjer med 2 desimaler

---

src/main/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieController.kt
src/main/kotlin/no/nav/faktureringskomponenten/domain/repositories/FakturaserieRepository.kt
src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt
src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt

Vi har en ganske stor rekursiv sql query, og jeg synes det er veldig
komplisert alerede. Tror det er bedre å filtrere på diverse
fakturastatuser i frontend istedenfor, når det kan komme flere ting å
filtrere på, vil denne bare bli større og mer uleselig. Fjerner derfor
denne.
https://jira.adeo.no/browse/MELOSYS-6078

MELOSYS 6078  fjern filter db

---

.github/workflows/pull-request.yml

1) https://github.com/gradle/gradle-build-action
>The gradle-build-action collects information about any Gradle executions that occur in a workflow, and reports these via a Job Summary, visible in the GitHub Actions UI.
gradle-build-action tar seg av caching også
2) Valider Gradle wrapper (se ev. https://github.com/gradle/wrapper-validation-action)

gradle-build-action og wrapper validering

---

src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandler.kt
src/main/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningsfakturaGenerator.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningBehandlerTest.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/avregning/AvregningIT.kt

https://jira.adeo.no/browse/MELOSYS-6060
Flere løpende avregninger på rad må kunne fungere. Tanken er å bruke linjene fra tidligere avregningsfaktura.
Å parse beskrivelsen er jo litt hacky, så det spørs om man bør lagre beregnet avregningsbeløp i stedet.
Å beregne alt på nytt virker ikke aktuelt: da kan kodeendringer gjør at man ikke finner riktig beløp som ble angitt på
en avregningslinje.
Koden er også kanskje litt vanskelig å skjønne, så jeg tenker det er bra å få flere tilbakemeldinger

6060 flere loepende avregninger

---

src/main/resources/db/migration/V22__opprettet_tidspunkt.sql

- opprettet_tidspunkt kunne ikke lages NOT NULL for eksisterende rader

MELOSYS 6238  auditing migrering fiks

---

.github/workflows/deploy-q2.yaml

https://jira.adeo.no/browse/MELOSYS-6280
fetch-depth=0 gjør at vi henter hele historikken, ellers hentes bare siste commit. Uten historikk kan vi ikke gjøre sammenligning med siste release og dermed ikke lage changelog. I api f.eks er dette med, så må ha blitt glemt i kopieringa

6280 deploy checkout hentet ikke historikk

---

src/main/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusService.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusServiceTest.kt

Denne PR'en fungerer som en extention av https://github.com/navikt/faktureringskomponenten/pull/107. 
Den logikken rundt duplikatsjekken av melding fra OEBS er jeg litt usikker på om det er riktig. Skal ha en gjennomgang med @thanglyphan senere i uken. Derfor har jeg ikke fokusert for mye på det.

6130: Tester for EksternFakturaStatusService

---

src/main/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusService.kt
src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/dto/Betalingsstatus.kt
src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/dto/ManglendeFakturabetalingDto.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/EksternFakturaStatusServiceTest.kt

Ser vi bruker  `...sstatus` overalt i Melosys ellers.
Feil meldt om på Slack: https://nav-it.slack.com/archives/C05AYQKUC0K/p1701252512871039

6130: Endre navn Betalingstatus -> Betalingsstatus

---

src/main/kotlin/no/nav/faktureringskomponenten/service/integration/kafka/dto/FakturaBestiltDto.kt
src/main/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapper.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceTest.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapperTest.kt

OEBS har vist mappet(?) dette feltet og kan ikke endre prod raskt. Så reverter det og beholder nytt navn på innsiden av vår model

6061 Reverter interface endring

---

nais/nais.yml
nais/vars-prod.json
nais/vars-q1.json
nais/vars-q2.json

Gjelder også db-g1-small
These machine types are configured to use a shared-core CPU, and are
designed to provide low-cost test and development instances only. Don't
use them for production instances.
(https://cloud.google.com/sql/docs/postgres/instance-settings#machine-type-2ndgen)

db-f1-micro, som er default, bør ikke brukes i prod

---

src/main/kotlin/no/nav/faktureringskomponenten/controller/AdminController.kt
src/main/kotlin/no/nav/faktureringskomponenten/controller/dto/FakturaResponseDto.kt
src/main/kotlin/no/nav/faktureringskomponenten/controller/mapper/ModelDtoMapperExtensions.kt

Melosys-API forventer fakturanummer som sifre. Bytter derfor identifikator til et randomt tall mellom 99990000 - 99999999. 
Legger også til fakturareferanse i DTO ettersom det vil gjøre at vi slipper å gå innpå databasen for å hente det hver gang.

NOJIRA: Random tall på simulert manglende innbetaling

---

src/main/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieController.kt
src/test/kotlin/no/nav/faktureringskomponenten/controller/FakturaserieControllerIT.kt

melosys-api forventer ny fakturaseriereferanse når vi kansellerer, mens faktureringskomponenten tidligere returnerte NO_CONTENT (204).
https://jira.adeo.no/browse/MELOSYS-6376

6376: Returner ny fakturaseriereferanse ved kansellering

---

src/test/kotlin/no/nav/faktureringskomponenten/TestFacktoryDsl.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaBestillingServiceTest.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/mappers/FakturaBestiltDtoMapperTest.kt

Rydder i bruk av navnet kreditreferanseNr som er faset ut.
https://github.com/navikt/faktureringskomponenten/pull/165

NOJIRA: Rydd i tester på bruk av gammel variabelnavn

---

src/main/kotlin/no/nav/faktureringskomponenten/config/CorrelationIdInterceptor.kt

Ved exception kalles afterCompletion med en gang og clearer MDC før det logges. Dermed kommer ikke correlationId med i error log for faktureringskomponenten når koden ble trigget av et ekstern kall. (noe som skjer når det feiler på opprettFakturaserie kalt fra melosys-api)

VAKT afterCompletion eksekveres for tidlig

---

src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieService.kt

Ikke en teknisk feil, men tyder på at saksbehandlere har opprettet flere saker enn nødvendig ref. https://jira.adeo.no/browse/MELOSYS-6820
(Ble innført i https://github.com/navikt/faktureringskomponenten/pull/174)

6820 fjern errorlogging

---

build.gradle.kts
src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaGenerator.kt
src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaIntervallPeriodisering.kt
src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaLinjeGenerator.kt
src/main/kotlin/no/nav/faktureringskomponenten/service/FakturaserieGenerator.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaGeneratorParameterizedTest.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaGeneratorTest.kt
src/test/kotlin/no/nav/faktureringskomponenten/service/FakturaIntervallPeriodiseringTest.kt

https://jira.adeo.no/browse/MELOSYS-6980
Jeg tenker at logikk for periodisering hører sammen med fakturaserier, samtidig trenger `FakturaGenerator` å vite om dagens dato og periodisering, for å kunne vite om fakturalinjer havner i en ny faktura.
Derfor har jeg flyttet logikk om periodisering i `FakturaserieGenerator`

6980 refaktorering når fakturaserie erstattes

---

src/main/kotlin/no/nav/faktureringskomponenten/service/AdminService.kt

Det feiler i OEBS når defaultverdien sendes (0)

NOJIRA: Negate enhetsprisPerMåned på admin-endepunkt

---

.github/workflows/deploy-dev.yaml

Deploy til q1 feiler akkurat nå, uten at jeg kan fort forklare hvorfor. Virker å være et problem med miljø i q1. Disabler midleritidig for å fikse vaktsaken.

Vakt: Midlertidig disable deploy til q1
